const client = window.supabase.createClient('https://doesaksrwklymiybkbvk.supabase.co', 'sb_publishable_Ik4yK4b2sTiuouF4n9_ztg_fMbLL0tY');
const $ = s => document.querySelector(s);
const monthKey = new Date().toISOString().slice(0, 7);
const monthName = new Intl.DateTimeFormat('ru-RU', { month: 'long', year: 'numeric' }).format(new Date()).replace(/^./, c => c.toUpperCase());
let user = null, state = { goals: [] }, reminderTimer = null;
const error = m => alert(m);
const reminderKey = () => `focus-hourly-reminders:${user?.id || 'guest'}`;
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {});

async function save() { if (!user) return; const { error: e } = await client.from('monthly_plans').upsert({ user_id: user.id, month_key: monthKey, plan: state }, { onConflict: 'user_id,month_key' }); if (e) error('Не удалось сохранить: ' + e.message); }
async function loadPlan() { const { data, error: e } = await client.from('monthly_plans').select('plan').eq('month_key', monthKey).maybeSingle(); if (e) { error('Не удалось загрузить план: ' + e.message); return; } state = data?.plan || { goals: [] }; renderGoals(); if (!state.goals.length) $('#onboarding').showModal(); }
async function openApp() { $('#authView').classList.add('hidden'); $('#appView').classList.remove('hidden'); $('#monthName').textContent = monthName; $('#setupMonth').textContent = monthName; $('#profileButton').textContent = (user.user_metadata?.name || user.email || 'Ф')[0].toUpperCase(); updateReminderUi(); startHourlyReminders(); await loadPlan(); }
function formatGoal(g) { return g.unit === '₽' ? `${g.done.toLocaleString('ru-RU')} / ${g.target.toLocaleString('ru-RU')} ₽` : `${g.done} / ${g.target} ${g.unit}`; }
function renderGoals() { const root = $('#goalGroups'); root.innerHTML = ''; const cats = ['Спорт', 'Семья', 'Финансы']; let done = 0, target = 0; cats.forEach(cat => { const goals = state.goals.filter(g => g.category === cat); if (!goals.length) return; const group = document.createElement('section'); group.className = 'group'; group.innerHTML = `<div class="group-head"><h2>${cat}</h2><span>${goals.length} целей</span></div><div class="goal-list"></div>`; const list = group.querySelector('.goal-list'); goals.forEach(g => { done += g.done; target += g.target; const pct = Math.round(g.done / g.target * 100), card = document.createElement('article'); card.className = 'goal-card'; card.innerHTML = `<div class="goal-top"><h3>${g.title}</h3><div><span class="goal-value">${formatGoal(g)}</span><button class="delete">×</button></div></div><div class="progress"><span style="width:${pct}%"></span></div><div class="goal-bottom"><span>${pct}% выполнено</span><input class="slider" type="range" min="0" max="${g.target}" value="${g.done}"></div>`; card.querySelector('.slider').oninput = async e => { g.done = Number(e.target.value); renderGoals(); await save(); }; card.querySelector('.delete').onclick = async () => { state.goals = state.goals.filter(x => x.id !== g.id); renderGoals(); await save(); }; list.append(card); }); root.append(group); }); const pct = target ? Math.round(done / target * 100) : 0; $('#progressText').textContent = pct + '%'; $('#totalProgress').style.width = pct + '%'; $('#progressNote').textContent = target ? `${done.toLocaleString('ru-RU')} из ${target.toLocaleString('ru-RU')} шагов выполнено.` : 'Добавь первую цель для этого месяца.'; }
async function addGoal(x) { state.goals.push({ id: crypto.randomUUID(), title: x.title.trim(), category: x.category, done: Math.min(Number(x.done), Number(x.target)), target: Number(x.target), unit: x.unit.trim() || 'раз' }); renderGoals(); await save(); }

function remindersEnabled() { return localStorage.getItem(reminderKey()) === 'true'; }
function updateReminderUi() { const supported = 'Notification' in window; $('#reminderToggle').checked = remindersEnabled(); $('#reminderToggle').disabled = !supported; $('#reminderStatus').textContent = !supported ? 'Уведомления не поддерживаются этим браузером.' : Notification.permission === 'denied' ? 'Уведомления заблокированы в настройках iPhone или браузера.' : remindersEnabled() ? 'Напоминания включены.' : 'Напоминания выключены.'; }
async function showReminder() { if (Notification.permission !== 'granted') return; const options = { body: 'Открой план и проверь прогресс по целям.', icon: 'favicon.png', badge: 'favicon.png', tag: 'focus-hourly-reminder', renotify: true }; if ('serviceWorker' in navigator) { const registration = await navigator.serviceWorker.ready; return registration.showNotification('Время проверить цели', options); } new Notification('Время проверить цели', options); }
function startHourlyReminders() { clearTimeout(reminderTimer); if (!remindersEnabled()) return; const scheduleNext = () => { const now = new Date(), next = new Date(now); next.setMinutes(0, 0, 0); next.setHours(now.getHours() + 1); reminderTimer = setTimeout(async () => { if (remindersEnabled()) await showReminder(); scheduleNext(); }, next - now); }; scheduleNext(); }
async function setReminders(enabled) { if (enabled && Notification.permission !== 'granted') { const permission = await Notification.requestPermission(); if (permission !== 'granted') { $('#reminderToggle').checked = false; updateReminderUi(); return; } } localStorage.setItem(reminderKey(), String(enabled)); updateReminderUi(); startHourlyReminders(); }

function showAuth(mode) { const name = $('#userName'); $('#authTitle').textContent = mode === 'login' ? 'Вход' : 'Регистрация'; name.closest('label').style.display = mode === 'login' ? 'none' : 'grid'; name.disabled = mode === 'login'; $('#authForm').dataset.mode = mode; $('#authDialog').showModal(); }
$('#openRegister').onclick = () => showAuth('register'); $('#openLogin').onclick = () => showAuth('login');
$('#authForm').onsubmit = async e => { e.preventDefault(); const email = $('#userEmail').value, password = $('#userPassword').value, mode = e.currentTarget.dataset.mode; const r = mode === 'login' ? await client.auth.signInWithPassword({ email, password }) : await client.auth.signUp({ email, password, options: { data: { name: $('#userName').value }, emailRedirectTo: location.href } }); if (r.error) return error(r.error.message); $('#authDialog').close(); if (!r.data.session) return error('Проверь почту и подтверди регистрацию, затем войди.'); user = r.data.user; await openApp(); };
$('#setupForm').onsubmit = async e => { e.preventDefault(); await addGoal({ title: $('#firstGoal').value, category: $('#firstCategory').value, done: $('#firstDone').value, target: $('#firstTarget').value, unit: 'раз' }); $('#onboarding').close(); };
$('#addGoal').onclick = () => $('#goalDialog').showModal();
$('#goalForm').onsubmit = async e => { e.preventDefault(); await addGoal({ title: $('#goalTitle').value, category: $('#goalCategory').value, done: $('#goalDone').value, target: $('#goalTarget').value, unit: $('#goalUnit').value }); e.currentTarget.reset(); $('#goalDone').value = 0; $('#goalTarget').value = 1; $('#goalUnit').value = 'раз'; $('#goalDialog').close(); };
$('#profileButton').onclick = () => { $('#accountEmail').textContent = user.email; updateReminderUi(); $('#profileDialog').showModal(); };
$('#reminderToggle').onchange = e => setReminders(e.target.checked);
$('#testReminder').onclick = async () => { if (Notification.permission !== 'granted') return setReminders(true); await showReminder(); };
$('#logoutButton').onclick = () => client.auth.signOut();
document.querySelectorAll('[data-close]').forEach(b => b.onclick = () => b.closest('dialog').close());
document.querySelectorAll('.tab').forEach(b => b.onclick = () => { document.querySelectorAll('.tab,.panel').forEach(x => x.classList.remove('active')); b.classList.add('active'); $('#' + b.dataset.tab).classList.add('active'); });
client.auth.getSession().then(({ data }) => { if (data.session) { user = data.session.user; openApp(); } });
client.auth.onAuthStateChange((_e, s) => { if (!s) { user = null; clearTimeout(reminderTimer); $('#appView').classList.add('hidden'); $('#authView').classList.remove('hidden'); } });
