const client=window.supabase.createClient('https://doesaksrwklymiybkbvk.supabase.co','sb_publishable_Ik4yK4b2sTiuouF4n9_ztg_fMbLL0tY');
const $=s=>document.querySelector(s),today=new Date(),currentKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;
let user=null,state={},selectedMonth=currentKey,itemType='debts',reminderTimer=null,availableMonths=[],goalAdding=false,itemAdding=false;
const error=m=>alert(m),types={debts:'долг',investments:'инвестицию',payments:'платёж'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
const monthLabel=k=>new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(+k.slice(0,4),+k.slice(5)-1,1)).replace(/^./,c=>c.toUpperCase());
const blank=()=>({goals:[],debts:[],investments:[],payments:[]});
const ensureState=()=>{state={...blank(),...state};Object.keys(blank()).forEach(k=>state[k]||=[])};
async function save(){if(!user)return;const{error:e}=await client.from('monthly_plans').upsert({user_id:user.id,month_key:selectedMonth,plan:state},{onConflict:'user_id,month_key'});if(e)error('Не удалось сохранить: '+e.message)}
async function loadPlan(){const{data,error:e}=await client.from('monthly_plans').select('plan').eq('month_key',selectedMonth).maybeSingle();if(e)return error('Не удалось загрузить план: '+e.message);state=data?.plan||blank();ensureState();renderAll();if(!state.goals.length&&selectedMonth===currentKey&&!$('#onboarding').open)$('#onboarding').showModal()}
function setAvatar(){const avatar=user?.user_metadata?.avatar,button=$('#profileButton');button.style.backgroundImage=avatar?`url("${avatar}")`:'';button.classList.toggle('has-avatar',!!avatar);if(!avatar)button.textContent=(user?.user_metadata?.name||user?.email||'Ф')[0].toUpperCase()}
async function refreshAvailableMonths(){const{data}=await client.from('monthly_plans').select('month_key').order('month_key',{ascending:false});if(data)availableMonths=data.map(x=>x.month_key)}
async function openApp(){ $('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');setAvatar();updateReminderUi();startHourlyReminders();refreshAvailableMonths();await setMonth(currentKey)}
async function setMonth(key){selectedMonth=key;$('#monthName').textContent=monthLabel(key);$('#setupMonth').textContent=monthLabel(key);await loadPlan()}
function format(g){return g.unit==='₽'?`${Number(g.done).toLocaleString('ru-RU')} / ${Number(g.target).toLocaleString('ru-RU')} ₽`:`${g.done} / ${g.target} ${g.unit}`}
function pct(g){return Math.max(0,Math.min(100,Math.round(Number(g.done)/Number(g.target)*100)))}
function card(g,collection){const progress=g.mode!=='check',p=progress?pct(g):g.done?100:0,el=document.createElement('article');el.className='goal-card';el.innerHTML=`<div class="goal-top"><h3>${g.title}</h3><button class="delete" aria-label="Удалить">×</button></div>${progress?`<div class="progress"><span style="width:${p}%"></span></div><div class="goal-controls"><button class="step" data-step="-1">−</button><input class="slider" type="range" min="0" max="${g.target}" value="${g.done}"><button class="step" data-step="1">+</button></div><div class="goal-bottom"><span class="goal-value">${format(g)}</span><span>${p}% выполнено</span></div>`:`<button class="checkpoint ${g.done?'done':''}"><i>${g.done?'✓':''}</i><span>${g.done?'Выполнено':'Отметить выполненным'}</span></button>`}`;
 const setDone=async n=>{g.done=Math.max(0,Math.min(Number(g.target),n));renderAll();await save()};
 if(progress){const slider=el.querySelector('.slider');slider.oninput=e=>{g.done=Number(e.target.value);el.querySelector('.progress span').style.width=pct(g)+'%';el.querySelector('.goal-value').textContent=format(g);el.querySelector('.goal-bottom span:last-child').textContent=pct(g)+'% выполнено';updateSummary()};slider.onchange=async()=>{await save();renderAll()};el.querySelectorAll('.step').forEach(b=>b.onclick=()=>setDone(Number(g.done)+Number(b.dataset.step)))}else el.querySelector('.checkpoint').onclick=()=>setDone(g.done?0:1);
 el.querySelector('.delete').onclick=async()=>{if(!confirm(`Удалить «${g.title}»?`))return;state[collection]=state[collection].filter(x=>x.id!==g.id);renderAll();await save()};return el}
function updateSummary(){const totals=state.goals.reduce((a,g)=>({done:a.done+Number(g.done),target:a.target+Number(g.target)}),{done:0,target:0}),p=totals.target?Math.round(totals.done/totals.target*100):0;$('#progressText').textContent=p+'%';$('#totalProgress').style.width=p+'%';$('#progressNote').textContent=totals.target?`${totals.done.toLocaleString('ru-RU')} из ${totals.target.toLocaleString('ru-RU')} шагов выполнено.`:'Добавь первую цель для этого месяца.'}
function renderGoals(){const root=$('#goalGroups');root.innerHTML='';const cats=['Спорт','Семья','Финансы'];cats.forEach(cat=>{const goals=state.goals.filter(g=>g.category===cat);if(!goals.length)return;const group=document.createElement('section');group.className='group';group.innerHTML=`<div class="group-head"><h2>${cat}</h2><span>${goals.length} целей</span></div><div class="goal-list"></div>`;const list=group.querySelector('.goal-list');goals.forEach(g=>list.append(card(g,'goals')));root.append(group)});updateSummary()}
function renderItems(collection){const root=$('#'+collection+'List');root.innerHTML='';const entries=state[collection];if(!entries.length)root.innerHTML='<div class="empty-panel"><p>Пока здесь нет записей.</p></div>';entries.forEach(x=>root.append(card(x,collection)))}
function renderAll(){renderGoals();['debts','investments','payments'].forEach(renderItems)}
async function addGoal(x){state.goals.push({id:crypto.randomUUID(),title:x.title.trim(),category:x.category,done:Math.min(Number(x.done),Number(x.target)),target:Number(x.target),unit:x.unit.trim()||'раз',mode:'progress'});renderAll();await save()}
async function addItem(x){state[itemType].push({id:crypto.randomUUID(),title:x.title.trim(),mode:x.mode,done:x.mode==='check'?0:Math.min(Number(x.done),Number(x.target)),target:x.mode==='check'?1:Number(x.target),unit:x.unit.trim()||'раз'});renderAll();await save()}
function renderPeriods(){const next=new Date(today.getFullYear(),today.getMonth()+1,1),nextKey=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`,keys=[...new Set([currentKey,nextKey,...availableMonths])].sort().reverse(),list=$('#periodList');list.innerHTML='';keys.forEach(key=>{const b=document.createElement('button');b.className='period-option'+(key===selectedMonth?' active':'');b.textContent=monthLabel(key);b.onclick=async()=>{$('#periodDialog').close();await setMonth(key)};list.append(b)})}
function openPeriods(){renderPeriods();$('#periodDialog').showModal()}
function reminderKey(){return`focus-hourly-reminders:${user?.id||'guest'}`}function remindersEnabled(){return localStorage.getItem(reminderKey())==='true'}
function updateReminderUi(){const supported='Notification'in window;$('#reminderToggle').checked=remindersEnabled();$('#reminderToggle').disabled=!supported;$('#reminderStatus').textContent=!supported?'Уведомления не поддерживаются этим браузером.':Notification.permission==='denied'?'Уведомления заблокированы в настройках iPhone или браузера.':remindersEnabled()?'Напоминания включены.':'Напоминания выключены.'}
async function showReminder(){if(Notification.permission!=='granted')return;const o={body:'Открой план и проверь прогресс по целям.',icon:'favicon.png',badge:'favicon.png',tag:'focus-hourly-reminder',renotify:true};if('serviceWorker'in navigator)return(await navigator.serviceWorker.ready).showNotification('Время проверить цели',o);new Notification('Время проверить цели',o)}
function startHourlyReminders(){clearTimeout(reminderTimer);if(!remindersEnabled())return;const schedule=()=>{const n=new Date(),next=new Date(n);next.setMinutes(0,0,0);next.setHours(n.getHours()+1);reminderTimer=setTimeout(async()=>{if(remindersEnabled())await showReminder();schedule()},next-n)};schedule()}
async function setReminders(enabled){if(enabled&&Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted'){updateReminderUi();return}}localStorage.setItem(reminderKey(),String(enabled));updateReminderUi();startHourlyReminders()}
function showAuth(mode){const name=$('#userName');$('#authTitle').textContent=mode==='login'?'Вход':'Регистрация';name.closest('label').style.display=mode==='login'?'none':'grid';name.disabled=mode==='login';$('#authForm').dataset.mode=mode;$('#authDialog').showModal()}
$('#openRegister').onclick=()=>showAuth('register');$('#openLogin').onclick=()=>showAuth('login');$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#userEmail').value,password=$('#userPassword').value,mode=e.currentTarget.dataset.mode,r=mode==='login'?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password,options:{data:{name:$('#userName').value},emailRedirectTo:location.href}});if(r.error)return error(r.error.message);$('#authDialog').close();if(!r.data.session)return error('Проверь почту и подтверди регистрацию, затем войди.');user=r.data.user;await openApp()};
$('#setupForm').onsubmit=async e=>{e.preventDefault();await addGoal({title:$('#firstGoal').value,category:$('#firstCategory').value,done:$('#firstDone').value,target:$('#firstTarget').value,unit:'раз'});$('#onboarding').close()};$('#addGoal').onclick=()=>$('#goalDialog').showModal();$('#goalForm').onsubmit=async e=>{e.preventDefault();if(goalAdding)return;goalAdding=true;const button=e.currentTarget.querySelector('[type="submit"]');button.disabled=true;$('#goalDialog').close();await addGoal({title:$('#goalTitle').value,category:$('#goalCategory').value,done:$('#goalDone').value,target:$('#goalTarget').value,unit:'раз'});e.currentTarget.reset();$('#goalDone').value=0;$('#goalTarget').value=1;button.disabled=false;goalAdding=false};
document.querySelectorAll('.add-item').forEach(b=>b.onclick=()=>{itemType=b.dataset.type;$('#itemDialogTitle').textContent='Новый '+types[itemType];$('#itemForm').reset();$('#itemCurrency').value='₽';$('#itemDialog').showModal()});$('#itemMode').onchange=e=>{$('#itemNumbers').classList.toggle('hidden',e.target.value==='check');$('#itemUnitWrap').classList.toggle('hidden',e.target.value==='check')};$('#itemForm').onsubmit=async e=>{e.preventDefault();if(itemAdding)return;itemAdding=true;const button=e.currentTarget.querySelector('[type="submit"]');button.disabled=true;$('#itemDialog').close();await addItem({title:$('#itemTitle').value,mode:$('#itemMode').value,done:$('#itemDone').value,target:$('#itemTarget').value,unit:$('#itemCurrency').value});button.disabled=false;itemAdding=false};
async function saveAvatar(file){if(!file)return;const source=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)}),image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=source}),canvas=document.createElement('canvas'),size=160;canvas.width=canvas.height=size;const c=canvas.getContext('2d'),scale=Math.max(size/image.width,size/image.height),w=image.width*scale,h=image.height*scale;c.drawImage(image,(size-w)/2,(size-h)/2,w,h);const avatar=canvas.toDataURL('image/jpeg',.8),{data,error:e}=await client.auth.updateUser({data:{avatar}});if(e)return error(e.message);user=data.user;setAvatar()}
$('#monthButton').onclick=openPeriods;$('#profileButton').onclick=()=>{$('#accountEmail').textContent=user.email;updateReminderUi();$('#profileDialog').showModal()};$('#avatarUpload').onchange=e=>saveAvatar(e.target.files[0]);$('#reminderToggle').onchange=e=>setReminders(e.target.checked);$('#testReminder').onclick=async()=>{if(Notification.permission!=='granted')return setReminders(true);await showReminder()};$('#logoutButton').onclick=()=>{$('#profileDialog').close();client.auth.signOut()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});client.auth.getSession().then(({data})=>{if(data.session){user=data.session.user;openApp()}});client.auth.onAuthStateChange((_e,s)=>{if(!s){user=null;clearTimeout(reminderTimer);$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}});
